language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
script: bundle exec rspec
before_script:
  - cp config/database.yml.example config/database.yml
  - mysql -e 'create database directory_test'
  - psql -c 'create database directory_test' -U postgres