language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
env:
  - DB=sqlite
  - DB=mysql
services:
  - elasticsearch
before_script:
  - cp config/database.yml.example config/database.yml
  - mysql -e 'create database directory_test'
  - bundle exec rake db:migrate RAILS_ENV=test
script: bundle exec rspec
