app:
  name: Directory
  scheme: https
  host: directory.biola.edu
  relative_url_root: /

release:
  phase: beta  # 'alpha' and 'beta' will enable the pre-release banner the layout

feedback:
  form_url: https://forms.biola.edu/information-technology/web-directory-feedback

secret_token: # Override this in settings.local.yml

api_base: api.biola.edu/directory/v1

urn_namespaces:
- "urn:biola:apps:directory:"
- "urn:biola:apps:all:"

cas:
  url: "https://login.biola.edu/cas"

email:
  enabled: true
  from: no-reply@biola.edu
  developer: appdev@biola.edu
  smtp:
    server: postfix.biola.edu

exceptions:
  mail_to:
  - appdev@biola.edu

feedback:
  mail_to: appsupport@biola.edu

biola_web_api:
  scheme: http
  host: localhost:3000
  script_name:
  version: v1
  access_id: # set in settings.local.yml
  secret_key: # set in settings.local.yml

elasticsearch:
  host:  # set in environment settings, leave nil for development
  index_name: 'directory'

profile_publisher:
  url:  # set in settings.local.yml in development

google_analytics:
  account: UA-31491589-5  # this is the testing/staging account
  domain: biola.edu
  enabled: false

pagination_limit: 30

roz:
  access_id: # set in settings.local.yml
  secret_key: # set in settings.local.yml

recaptcha:
  sitekey: # set in settings.local.yml
  secret: # set in settings.local.yml
