biola_web_api:
  scheme: https
  host: api.biola.edu
  script_name: web

profile_publisher:
  url: https://wcms.biola.edu/profiles

elasticsearch:
  host: http://elastic1a.prod.biola.edu:9200
  index_name: directory

google_analytics:
  account: UA-31491589-10
  domain: biola.edu
  enabled: true

roz:
  files_base_url: http://assets.biola.edu
  access_id: 825942544431112402
