biola_web_api:
  scheme: https
  host: api.biola.edu
  script_name: web

profile_publisher:
  url: https://wcms.biola.edu/profiles

elasticsearch:
  host: http://elastic1a.prod.biola.edu:9200
  index_name: directory
