app:
  name: Directory
  scheme: https
  host: www.biola.edu
  relative_url_root: /directory

biola_web_api:
  scheme: https
  host: api.biola.edu
  script_name: web

profile_publisher:
  url: https://wcms.biola.edu/profiles

elasticsearch:
  hosts:
  - elastic1a.prod.biola.edu
  - elastic1b.prod.biola.edu
  index_name: directory

google_analytics:
  account: UA-31491589-10
  domain: biola.edu
  enabled: true

roz:
  files_base_url: http://assets.biola.edu
  access_id: 825942544431112402
