app:
  name: Directory
  scheme: https
  host: www.staging.biola.edu
  relative_url_root: /directory

biola_web_api:
  scheme: https
  host: api.staging.biola.edu
  script_name: web

profile_publisher:
  url: https://wcms.staging.biola.edu/profiles

elasticsearch:
  hosts:
  - elastic1.staging.biola.edu
  index_name: 'directory'

roz:
  files_base_url: http://assets.staging.biola.edu
  access_id: 240616938440200063
