biola_web_api:
  scheme: https
  host: api.staging.biola.edu
  script_name: web

profile_publisher:
  url: https://wcms.staging.biola.edu/profiles

elasticsearch:
  host: http://elastic1.staging.biola.edu:9200
  index_name: 'directory'

roz:
  files_base_url: http://assets.staging.biola.edu
  access_id: 240616938440200063
